{ config, pkgs, ... }:

{
  home.packages = [
    pkgs.ghostty
  ];

  xdg.configFile."ghostty/config".text = ''
    # Managed by Home Manager.
    # Runtime colors are generated by scripts/theme-select.
    config-file = ?${config.xdg.configHome}/theme/current/ghostty.conf

    font-family = JetBrainsMono Nerd Font
    font-size = 12

    background-opacity = 0.88
    background-opacity-cells = true
    background-blur = false

    cursor-style = block
    cursor-style-blink = false
    mouse-hide-while-typing = true
    mouse-scroll-multiplier = 5

    scrollback-limit = 10000000
    scrollbar = never

    window-decoration = none
    window-padding-x = 10
    window-padding-y = 10
    window-padding-balance = true
    window-padding-color = background
    window-new-tab-position = end
    window-show-tab-bar = auto
    window-save-state = default
    window-theme = ghostty

    shell-integration = detect
    shell-integration-features = cursor,title,ssh-env
    confirm-close-surface = false

    keybind = alt+enter=new_window
    keybind = alt+w=close_surface
    keybind = alt+right=next_tab
    keybind = alt+left=previous_tab
    keybind = alt+backslash=new_split:right
    keybind = alt+minus=new_split:down
    keybind = alt+h=goto_split:left
    keybind = alt+j=goto_split:down
    keybind = alt+k=goto_split:up
    keybind = alt+l=goto_split:right
    keybind = alt+equal=equalize_splits
    keybind = alt+z=toggle_split_zoom
    keybind = alt+c=copy_to_clipboard
    keybind = alt+v=paste_from_clipboard
    keybind = ctrl+shift+c=copy_to_clipboard
    keybind = ctrl+shift+v=paste_from_clipboard
    keybind = ctrl+shift+comma=reload_config
    keybind = ctrl+shift+p=toggle_command_palette
  '';
}
