write_btop_theme() {
  prepare_target "$config_home/btop/themes/sky.theme"
  cat > "$config_home/btop/themes/sky.theme" <<EOF
# Generated by theme-select from $style.
theme[main_bg]="$(hex '.[$style].semantic.background')"
theme[main_fg]="$(hex '.[$style].semantic.foreground')"
theme[title]="$(hex '.[$style].semantic.accent')"
theme[hi_fg]="$(hex '.[$style].semantic.accent')"
theme[selected_bg]="$(hex '.[$style].semantic.surfaceStrong')"
theme[selected_fg]="$(hex '.[$style].semantic.foreground')"
theme[inactive_fg]="$(hex '.[$style].semantic.muted')"
theme[graph_text]="$(hex '.[$style].semantic.muted')"
theme[meter_bg]="$(hex '.[$style].semantic.surface')"
theme[proc_misc]="$(hex '.[$style].semantic.warning')"
theme[cpu_box]="$(hex '.[$style].semantic.border')"
theme[mem_box]="$(hex '.[$style].semantic.border')"
theme[net_box]="$(hex '.[$style].semantic.border')"
theme[proc_box]="$(hex '.[$style].semantic.border')"
theme[div_line]="$(hex '.[$style].semantic.border')"
theme[temp_start]="$(hex '.[$style].semantic.success')"
theme[temp_mid]="$(hex '.[$style].semantic.warning')"
theme[temp_end]="$(hex '.[$style].semantic.danger')"
theme[cpu_start]="$(hex '.[$style].semantic.success')"
theme[cpu_mid]="$(hex '.[$style].semantic.warning')"
theme[cpu_end]="$(hex '.[$style].semantic.danger')"
theme[free_start]="$(hex '.[$style].semantic.danger')"
theme[free_mid]="$(hex '.[$style].semantic.warning')"
theme[free_end]="$(hex '.[$style].semantic.success')"
theme[cached_start]="$(hex '.[$style].semantic.accentAlt')"
theme[cached_mid]="$(hex '.[$style].semantic.accent')"
theme[cached_end]="$(hex '.[$style].semantic.success')"
theme[available_start]="$(hex '.[$style].semantic.danger')"
theme[available_mid]="$(hex '.[$style].semantic.warning')"
theme[available_end]="$(hex '.[$style].semantic.success')"
theme[used_start]="$(hex '.[$style].semantic.success')"
theme[used_mid]="$(hex '.[$style].semantic.warning')"
theme[used_end]="$(hex '.[$style].semantic.danger')"
theme[download_start]="$(hex '.[$style].semantic.accent')"
theme[download_mid]="$(hex '.[$style].semantic.accentAlt')"
theme[download_end]="$(hex '.[$style].semantic.success')"
theme[upload_start]="$(hex '.[$style].semantic.warning')"
theme[upload_mid]="$(hex '.[$style].semantic.danger')"
theme[upload_end]="$(hex '.[$style].semantic.danger')"
EOF
}

write_bat_theme() {
  mkdir -p "$config_home/bat/themes"
  prepare_target "$config_home/bat/config"
  cat > "$config_home/bat/config" <<'EOF'
--theme="Sky"
--style="numbers,changes,header"
EOF

  prepare_target "$config_home/bat/themes/Sky.tmTheme"
  cat > "$config_home/bat/themes/Sky.tmTheme" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>name</key><string>Sky</string>
<key>settings</key><array>
<dict><key>settings</key><dict>
<key>background</key><string>$(hex '.[$style].semantic.background')</string>
<key>foreground</key><string>$(hex '.[$style].semantic.foreground')</string>
<key>caret</key><string>$(hex '.[$style].semantic.accent')</string>
<key>selection</key><string>$(hex '.[$style].semantic.surfaceStrong')</string>
<key>lineHighlight</key><string>$(hex '.[$style].semantic.surface')</string>
</dict></dict>
<dict><key>scope</key><string>comment</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.muted')</string><key>fontStyle</key><string>italic</string></dict></dict>
<dict><key>scope</key><string>string</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.success')</string></dict></dict>
<dict><key>scope</key><string>keyword, storage</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.accentAlt')</string></dict></dict>
<dict><key>scope</key><string>entity.name.function, support.function</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].terminal.blue')</string></dict></dict>
<dict><key>scope</key><string>constant.numeric, constant.language</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.warning')</string></dict></dict>
<dict><key>scope</key><string>invalid</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.danger')</string></dict></dict>
</array></dict></plist>
EOF
}
