write_btop_theme() {
  prepare_target "$config_home/btop/themes/sky.theme"
  cat > "$config_home/btop/themes/sky.theme" <<EOF
# Generated by theme-select from $style.
theme[main_bg]="$(hex '.[$style].semantic.background')"
theme[main_fg]="$(hex '.[$style].semantic.foreground')"
theme[title]="$(hex '.[$style].semantic.accent')"
theme[hi_fg]="$(hex '.[$style].semantic.accent')"
theme[selected_bg]="$(hex '.[$style].semantic.surfaceStrong')"
theme[selected_fg]="$(hex '.[$style].semantic.foreground')"
theme[inactive_fg]="$(hex '.[$style].semantic.muted')"
theme[graph_text]="$(hex '.[$style].semantic.muted')"
theme[meter_bg]="$(hex '.[$style].semantic.surface')"
theme[proc_misc]="$(hex '.[$style].semantic.warning')"
theme[cpu_box]="$(hex '.[$style].semantic.border')"
theme[mem_box]="$(hex '.[$style].semantic.border')"
theme[net_box]="$(hex '.[$style].semantic.border')"
theme[proc_box]="$(hex '.[$style].semantic.border')"
theme[div_line]="$(hex '.[$style].semantic.border')"
theme[temp_start]="$(hex '.[$style].semantic.success')"
theme[temp_mid]="$(hex '.[$style].semantic.warning')"
theme[temp_end]="$(hex '.[$style].semantic.danger')"
theme[cpu_start]="$(hex '.[$style].semantic.success')"
theme[cpu_mid]="$(hex '.[$style].semantic.warning')"
theme[cpu_end]="$(hex '.[$style].semantic.danger')"
theme[free_start]="$(hex '.[$style].semantic.danger')"
theme[free_mid]="$(hex '.[$style].semantic.warning')"
theme[free_end]="$(hex '.[$style].semantic.success')"
theme[cached_start]="$(hex '.[$style].semantic.accentAlt')"
theme[cached_mid]="$(hex '.[$style].semantic.accent')"
theme[cached_end]="$(hex '.[$style].semantic.success')"
theme[available_start]="$(hex '.[$style].semantic.danger')"
theme[available_mid]="$(hex '.[$style].semantic.warning')"
theme[available_end]="$(hex '.[$style].semantic.success')"
theme[used_start]="$(hex '.[$style].semantic.success')"
theme[used_mid]="$(hex '.[$style].semantic.warning')"
theme[used_end]="$(hex '.[$style].semantic.danger')"
theme[download_start]="$(hex '.[$style].semantic.accent')"
theme[download_mid]="$(hex '.[$style].semantic.accentAlt')"
theme[download_end]="$(hex '.[$style].semantic.success')"
theme[upload_start]="$(hex '.[$style].semantic.warning')"
theme[upload_mid]="$(hex '.[$style].semantic.danger')"
theme[upload_end]="$(hex '.[$style].semantic.danger')"
EOF
}

write_bat_theme() {
  mkdir -p "$config_home/bat/themes"
  prepare_target "$config_home/bat/config"
  cat > "$config_home/bat/config" <<'EOF'
--theme="Sky"
--style="numbers,changes,header"
EOF

  prepare_target "$config_home/bat/themes/Sky.tmTheme"
  cat > "$config_home/bat/themes/Sky.tmTheme" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>name</key><string>Sky</string>
<key>settings</key><array>
<dict><key>settings</key><dict>
<key>background</key><string>$(hex '.[$style].semantic.background')</string>
<key>foreground</key><string>$(hex '.[$style].semantic.foreground')</string>
<key>caret</key><string>$(hex '.[$style].semantic.accent')</string>
<key>selection</key><string>$(hex '.[$style].semantic.surfaceStrong')</string>
<key>lineHighlight</key><string>$(hex '.[$style].semantic.surface')</string>
</dict></dict>
<dict><key>scope</key><string>comment</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.muted')</string><key>fontStyle</key><string>italic</string></dict></dict>
<dict><key>scope</key><string>string</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.success')</string></dict></dict>
<dict><key>scope</key><string>keyword, storage</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.accentAlt')</string></dict></dict>
<dict><key>scope</key><string>entity.name.function, support.function</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].terminal.blue')</string></dict></dict>
<dict><key>scope</key><string>constant.numeric, constant.language</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.warning')</string></dict></dict>
<dict><key>scope</key><string>invalid</string><key>settings</key><dict><key>foreground</key><string>$(hex '.[$style].semantic.danger')</string></dict></dict>
</array></dict></plist>
EOF
}

write_aerc_styleset() {
  prepare_target "$current_dir/aerc/stylesets/sky"
  cat > "$current_dir/aerc/stylesets/sky" <<EOF
# ============================================
# SKY — aerc styleset
# Generated by theme-select from $style.
# ============================================

*.default                            = true
*.normal                             = true
*.fg                                 = $(hex '.[$style].semantic.foreground')
*.bg                                 = default

# Global selection
*.selected.fg                        = $(hex '.[$style].semantic.selectionForeground')
*.selected.bg                        = $(hex '.[$style].semantic.selectionBackground')
*.selected.bold                      = true

# Title bars / tabs
title.fg                             = $(hex '.[$style].semantic.selectionForeground')
title.bg                             = $(hex '.[$style].semantic.accent')
title.bold                           = true
header.fg                            = $(hex '.[$style].semantic.accent')
header.bold                          = true

# Status line
statusline_default.fg                = $(hex '.[$style].semantic.foreground')
statusline_default.bg                = $(hex '.[$style].semantic.surfaceStrong')
statusline_error.fg                  = $(hex '.[$style].semantic.danger')
statusline_error.bg                  = $(hex '.[$style].semantic.surfaceStrong')
statusline_error.bold                = true
statusline_warning.fg                = $(hex '.[$style].semantic.warning')
statusline_warning.bg                = $(hex '.[$style].semantic.surfaceStrong')
statusline_success.fg                = $(hex '.[$style].semantic.success')
statusline_success.bg                = $(hex '.[$style].semantic.surfaceStrong')

# Message list
msglist_default.fg                   = $(hex '.[$style].semantic.foreground')
msglist_unread.fg                    = $(hex '.[$style].semantic.accent')
msglist_unread.bold                  = true
msglist_read.fg                      = $(hex '.[$style].semantic.muted')
msglist_flagged.fg                   = $(hex '.[$style].semantic.warning')
msglist_flagged.bold                 = true
msglist_deleted.fg                   = $(hex '.[$style].semantic.muted')
msglist_marked.fg                    = $(hex '.[$style].semantic.selectionForeground')
msglist_marked.bg                    = $(hex '.[$style].semantic.warning')
msglist_result.fg                    = $(hex '.[$style].semantic.success')
msglist_answered.fg                  = $(hex '.[$style].semantic.success')
msglist_forwarded.fg                 = $(hex '.[$style].palette.darkCyan')

# Directory list
dirlist_default.fg                   = $(hex '.[$style].palette.fgAlt')
dirlist_unread.fg                    = $(hex '.[$style].semantic.accent')
dirlist_unread.bold                  = true
dirlist_recent.fg                    = $(hex '.[$style].semantic.warning')

# Borders and separators
border.fg                            = $(hex '.[$style].semantic.border')

# Completion
completion_default.fg                = $(hex '.[$style].semantic.foreground')
completion_default.bg                = $(hex '.[$style].semantic.surfaceStrong')
completion_pill.fg                   = $(hex '.[$style].semantic.selectionForeground')
completion_pill.bg                   = $(hex '.[$style].semantic.accent')

# Tab bar
tab.fg                               = $(hex '.[$style].semantic.muted')
tab.bg                               = $(hex '.[$style].semantic.background')
tab.selected.fg                      = $(hex '.[$style].semantic.selectionForeground')
tab.selected.bg                      = $(hex '.[$style].semantic.accent')
tab.selected.bold                    = true

[viewer]
*.normal                             = true
header.fg                            = $(hex '.[$style].semantic.accent')
header.bold                          = true
header.value.fg                      = $(hex '.[$style].semantic.foreground')
EOF
}

write_yazi_theme() {
  local source="$config_home/theme/yazi/$style.toml"

  prepare_target "$current_dir/yazi.toml"
  if [ -r "$source" ]; then
    cp "$source" "$current_dir/yazi.toml"
  elif [ ! -e "$current_dir/yazi.toml" ]; then
    cat > "$current_dir/yazi.toml" <<EOF
# Generated by theme-select from $style.
# The Nix-built Yazi theme source was not available at:
# $source
EOF
  fi
}
