write_mako_config() {
  prepare_target "$current_dir/mako.conf"
  cat > "$current_dir/mako.conf" <<EOF
# Generated by theme-select from $style.
font=JetBrainsMono Nerd Font 11
background-color=$(hex '.[$style].semantic.surface')ee
text-color=$(hex '.[$style].semantic.foreground')ff
border-color=$(hex '.[$style].semantic.accent')55
progress-color=over $(hex '.[$style].semantic.accent')88
width=360
height=110
margin=16
padding=12
border-size=1
border-radius=10
default-timeout=5000
anchor=top-right
EOF
}

write_gtk_config() {
  mkdir -p "$config_home/gtk-2.0" "$config_home/gtk-3.0" "$config_home/gtk-4.0"
  local prefer_dark=1
  local icon_theme="Papirus-Dark"
  [ "$(theme_flavor)" = "light" ] && prefer_dark=0
  [ "$(theme_flavor)" = "light" ] && icon_theme="Papirus"

  prepare_target "$config_home/gtk-2.0/gtkrc"
  cat > "$config_home/gtk-2.0/gtkrc" <<EOF
# Generated by theme-select from $style.
gtk-theme-name="Adwaita"
gtk-icon-theme-name="$icon_theme"
gtk-cursor-theme-name="Bibata-Modern-Ice"
gtk-cursor-theme-size=24
gtk-font-name="Inter 11"
gtk-color-scheme="bg_color:$(hex '.[$style].semantic.background')\nfg_color:$(hex '.[$style].semantic.foreground')\nbase_color:$(hex '.[$style].semantic.surface')\ntext_color:$(hex '.[$style].semantic.foreground')\nselected_bg_color:$(hex '.[$style].semantic.accent')\nselected_fg_color:$(hex '.[$style].semantic.selectionForeground')"
EOF

  for version in gtk-3.0 gtk-4.0; do
    prepare_target "$config_home/$version/settings.ini"
    cat > "$config_home/$version/settings.ini" <<EOF
[Settings]
gtk-application-prefer-dark-theme=$prefer_dark
gtk-theme-name=Adwaita
gtk-icon-theme-name=$icon_theme
gtk-cursor-theme-name=Bibata-Modern-Ice
gtk-cursor-theme-size=24
gtk-font-name=Inter 11
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
EOF

    prepare_target "$config_home/$version/gtk.css"
    cat > "$config_home/$version/gtk.css" <<EOF
@define-color theme_bg_color $(hex '.[$style].semantic.background');
@define-color theme_fg_color $(hex '.[$style].semantic.foreground');
@define-color theme_base_color $(hex '.[$style].semantic.surface');
@define-color theme_selected_bg_color $(hex '.[$style].semantic.accent');
@define-color theme_selected_fg_color $(hex '.[$style].semantic.selectionForeground');
@define-color borders $(hex '.[$style].semantic.border');
EOF
  done
}

write_qt_config() {
  local icon_theme="Papirus-Dark"
  [ "$(hex '.[$style].flavor')" = "light" ] && icon_theme="Papirus"

  local window="$(hex '.[$style].semantic.background')"
  local window_text="$(hex '.[$style].semantic.foreground')"
  local base="$(hex '.[$style].semantic.surface')"
  local alternate="$(hex '.[$style].semantic.surfaceStrong')"
  local text="$(hex '.[$style].semantic.foreground')"
  local button="$(hex '.[$style].semantic.surface')"
  local button_text="$(hex '.[$style].semantic.foreground')"
  local bright_text="$(hex '.[$style].semantic.selectionForeground')"
  local highlight="$(hex '.[$style].semantic.accent')"
  local highlighted_text="$(hex '.[$style].semantic.selectionForeground')"
  local disabled_text="$(hex '.[$style].semantic.muted')"
  local link="$(hex '.[$style].semantic.accent')"
  local visited_link="$(hex '.[$style].semantic.accentAlt')"
  local tooltip_base="$(hex '.[$style].semantic.surfaceStrong')"
  local tooltip_text="$(hex '.[$style].semantic.foreground')"

  # Qt palette order: Window, WindowText, Base, AlternateBase, ToolTipBase,
  # ToolTipText, Text, Button, ButtonText, BrightText, Light, Midlight, Dark,
  # Mid, Shadow, Highlight, HighlightedText, Link, LinkVisited, NoRole,
  # PlaceholderText.
  local active_colors="$window, $window_text, $base, $alternate, $tooltip_base, $tooltip_text, $text, $button, $button_text, $bright_text, $alternate, $button, $(hex '.[$style].semantic.border'), $(hex '.[$style].semantic.border'), $(hex '.[$style].palette.base0'), $highlight, $highlighted_text, $link, $visited_link, $window, $disabled_text"
  local disabled_colors="$window, $disabled_text, $base, $alternate, $tooltip_base, $tooltip_text, $disabled_text, $button, $disabled_text, $bright_text, $alternate, $button, $(hex '.[$style].semantic.border'), $(hex '.[$style].semantic.border'), $(hex '.[$style].palette.base0'), $highlight, $highlighted_text, $link, $visited_link, $window, $disabled_text"

  for toolkit in qt5ct qt6ct; do
    mkdir -p "$config_home/$toolkit/colors" "$config_home/$toolkit/qss"

    prepare_target "$config_home/$toolkit/colors/Sky.conf"
    cat > "$config_home/$toolkit/colors/Sky.conf" <<EOF
[ColorScheme]
active_colors=$active_colors
disabled_colors=$disabled_colors
inactive_colors=$active_colors
EOF

    prepare_target "$config_home/$toolkit/$toolkit.conf"
    cat > "$config_home/$toolkit/$toolkit.conf" <<EOF
[Appearance]
color_scheme_path=$config_home/$toolkit/colors/Sky.conf
custom_palette=true
icon_theme=$icon_theme
standard_dialogs=default
style=Fusion

[Fonts]
fixed="JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0"
general="Inter,11,-1,5,50,0,0,0,0,0"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray()
EOF
  done
}

write_kdeglobals() {
  local icon_theme="Papirus-Dark"
  [ "$(hex '.[$style].flavor')" = "light" ] && icon_theme="Papirus"

  prepare_target "$config_home/kdeglobals"
  cat > "$config_home/kdeglobals" <<EOF
# Generated by theme-select from $style.
[General]
ColorScheme=Sky
Name=Sky
shadeSortColumn=true

[Icons]
Theme=$icon_theme

[KDE]
widgetStyle=Fusion

[Colors:Window]
BackgroundNormal=$(hex '.[$style].semantic.background')
ForegroundNormal=$(hex '.[$style].semantic.foreground')
DecorationFocus=$(hex '.[$style].semantic.accent')
DecorationHover=$(hex '.[$style].semantic.accentAlt')

[Colors:View]
BackgroundNormal=$(hex '.[$style].semantic.surface')
ForegroundNormal=$(hex '.[$style].semantic.foreground')
BackgroundAlternate=$(hex '.[$style].semantic.surfaceStrong')
DecorationFocus=$(hex '.[$style].semantic.accent')
DecorationHover=$(hex '.[$style].semantic.accentAlt')

[Colors:Button]
BackgroundNormal=$(hex '.[$style].semantic.surface')
ForegroundNormal=$(hex '.[$style].semantic.foreground')
DecorationFocus=$(hex '.[$style].semantic.accent')
DecorationHover=$(hex '.[$style].semantic.accentAlt')

[Colors:Selection]
BackgroundNormal=$(hex '.[$style].semantic.accent')
ForegroundNormal=$(hex '.[$style].semantic.selectionForeground')
DecorationFocus=$(hex '.[$style].semantic.accent')
DecorationHover=$(hex '.[$style].semantic.accentAlt')

[Colors:Tooltip]
BackgroundNormal=$(hex '.[$style].semantic.surfaceStrong')
ForegroundNormal=$(hex '.[$style].semantic.foreground')
EOF
}
