write_emacs_theme() {
  prepare_target "$current_dir/emacs-theme.el"
  cat > "$current_dir/emacs-theme.el" <<EOF
;;; Generated by theme-select from $style. -*- lexical-binding: t; -*-

(setq sk/theme
      '((foreground . "$(hex '.[$style].semantic.foreground')")
        (background . "$(hex '.[$style].semantic.background')")
        (surface . "$(hex '.[$style].semantic.surface')")
        (surface-strong . "$(hex '.[$style].semantic.surfaceStrong')")
        (border . "$(hex '.[$style].semantic.border')")
        (border-active . "$(hex '.[$style].semantic.borderActive')")
        (accent . "$(hex '.[$style].semantic.accent')")
        (accent-alt . "$(hex '.[$style].semantic.accentAlt')")
        (muted . "$(hex '.[$style].semantic.muted')")
        (success . "$(hex '.[$style].semantic.success')")
        (warning . "$(hex '.[$style].semantic.warning')")
        (danger . "$(hex '.[$style].semantic.danger')")
        (selection-foreground . "$(hex '.[$style].semantic.selectionForeground')")
        (selection-background . "$(hex '.[$style].semantic.selectionBackground')")
        (string . "$(hex '.[$style].semantic.success')")
        (function . "$(hex '.[$style].semantic.accent')")
        (keyword . "$(hex '.[$style].semantic.accentAlt')")
        (number . "$(hex '.[$style].semantic.warning')")
        (type . "$(hex '.[$style].semantic.warning')")
        (builtin . "$(hex '.[$style].palette.teal')")
        (preprocessor . "$(hex '.[$style].palette.orange')")
        (comment . "$(hex '.[$style].semantic.muted')")))
EOF
}
