write_nvim_theme() {
  prepare_target "$current_dir/nvim.lua"
  cat > "$current_dir/nvim.lua" <<EOF
-- Generated by theme-select from $style.

return {
  name = "$style",
  flavor = "$(theme_flavor)",
  foreground = "$(hex '.[$style].semantic.foreground')",
  background = "$(hex '.[$style].semantic.background')",
  surface = "$(hex '.[$style].semantic.surface')",
  surface_strong = "$(hex '.[$style].semantic.surfaceStrong')",
  border = "$(hex '.[$style].semantic.border')",
  border_active = "$(hex '.[$style].semantic.borderActive')",
  accent = "$(hex '.[$style].semantic.accent')",
  accent_alt = "$(hex '.[$style].semantic.accentAlt')",
  muted = "$(hex '.[$style].semantic.muted')",
  success = "$(hex '.[$style].semantic.success')",
  warning = "$(hex '.[$style].semantic.warning')",
  danger = "$(hex '.[$style].semantic.danger')",
  selection_foreground = "$(hex '.[$style].semantic.selectionForeground')",
  selection_background = "$(hex '.[$style].semantic.selectionBackground')",
  string = "$(hex '.[$style].semantic.success')",
  ["function"] = "$(hex '.[$style].semantic.accent')",
  keyword = "$(hex '.[$style].semantic.accentAlt')",
  number = "$(hex '.[$style].semantic.warning')",
  type = "$(hex '.[$style].semantic.warning')",
  builtin = "$(hex '.[$style].palette.teal')",
  preprocessor = "$(hex '.[$style].palette.orange')",
  comment = "$(hex '.[$style].semantic.muted')",
  terminal = {
    black = "$(hex '.[$style].terminal.black')",
    bright_black = "$(hex '.[$style].terminal.brightBlack')",
    red = "$(hex '.[$style].terminal.red')",
    bright_red = "$(hex '.[$style].terminal.brightRed')",
    green = "$(hex '.[$style].terminal.green')",
    bright_green = "$(hex '.[$style].terminal.brightGreen')",
    yellow = "$(hex '.[$style].terminal.yellow')",
    bright_yellow = "$(hex '.[$style].terminal.brightYellow')",
    blue = "$(hex '.[$style].terminal.blue')",
    bright_blue = "$(hex '.[$style].terminal.brightBlue')",
    magenta = "$(hex '.[$style].terminal.magenta')",
    bright_magenta = "$(hex '.[$style].terminal.brightMagenta')",
    cyan = "$(hex '.[$style].terminal.cyan')",
    bright_cyan = "$(hex '.[$style].terminal.brightCyan')",
    white = "$(hex '.[$style].terminal.white')",
    bright_white = "$(hex '.[$style].terminal.brightWhite')",
  },
}
EOF
}
