write_kitty_theme() {
  prepare_target "$current_dir/kitty.conf"
  cat > "$current_dir/kitty.conf" <<EOF
# Generated by theme-select from $style.
foreground $(hex '.[$style].semantic.foreground')
background $(hex '.[$style].semantic.background')
selection_foreground $(hex '.[$style].semantic.selectionForeground')
selection_background $(hex '.[$style].semantic.selectionBackground')

cursor $(hex '.[$style].semantic.accent')
cursor_text_color $(hex '.[$style].semantic.selectionForeground')
url_color $(hex '.[$style].semantic.accent')

active_border_color $(hex '.[$style].semantic.accent')
inactive_border_color $(hex '.[$style].semantic.border')
bell_border_color $(hex '.[$style].semantic.warning')

active_tab_foreground $(hex '.[$style].semantic.selectionForeground')
active_tab_background $(hex '.[$style].semantic.accent')
inactive_tab_foreground $(hex '.[$style].semantic.foreground')
inactive_tab_background $(hex '.[$style].semantic.surface')
tab_bar_background $(hex '.[$style].semantic.background')

color0  $(hex '.[$style].terminal.black')
color1  $(hex '.[$style].terminal.red')
color2  $(hex '.[$style].terminal.green')
color3  $(hex '.[$style].terminal.yellow')
color4  $(hex '.[$style].terminal.blue')
color5  $(hex '.[$style].terminal.magenta')
color6  $(hex '.[$style].terminal.cyan')
color7  $(hex '.[$style].terminal.white')
color8  $(hex '.[$style].terminal.brightBlack')
color9  $(hex '.[$style].terminal.brightRed')
color10 $(hex '.[$style].terminal.brightGreen')
color11 $(hex '.[$style].terminal.brightYellow')
color12 $(hex '.[$style].terminal.brightBlue')
color13 $(hex '.[$style].terminal.brightMagenta')
color14 $(hex '.[$style].terminal.brightCyan')
color15 $(hex '.[$style].terminal.brightWhite')
EOF
}
write_starship_config() {
  prepare_target "$current_dir/starship.toml"
  cat > "$current_dir/starship.toml" <<EOF
# Generated by theme-select from $style.
add_newline = true
format = "\$directory\$git_branch\$git_status\n\$character"

[os]
disabled = false
style = "fg:$(hex '.[$style].semantic.success')"
format = "[\$symbol](\$style)"

[os.symbols]
NixOS = " "
Macos = " "
Ubuntu = " "
Arch = "󰣇 "
Debian = " "
Fedora = " "
Linux = " "

[shell]
disabled = false
style = "fg:$(hex '.[$style].semantic.muted')"
bash_indicator = " bash"
zsh_indicator = " zsh"
fish_indicator = "󰈺 fish"
unknown_indicator = " sh"
format = "[\$indicator ](\$style)"

[username]
show_always = true
style_user = "fg:$(hex '.[$style].semantic.muted')"
style_root = "fg:$(hex '.[$style].semantic.danger') bold"
format = "[ \$user ](\$style)"

[hostname]
ssh_only = true
style = "fg:$(hex '.[$style].semantic.muted')"
format = "[@\$hostname ](\$style)"

[directory]
style = "fg:$(hex '.[$style].semantic.foreground') bg:$(hex '.[$style].semantic.surfaceStrong')"
format = "[ \$path ](\$style)[ ](fg:$(hex '.[$style].semantic.muted'))"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"

[directory.substitutions]
Documents = "󰈙"
Downloads = ""
Music = "󰝚"
Pictures = ""
Videos = "󰕧"
nixos-dotfiles = ""

[git_branch]
symbol = ""
style = "fg:$(hex '.[$style].semantic.accent')"
format = "[󰊢 \$branch ](\$style)"

[git_status]
style = "fg:$(hex '.[$style].semantic.muted')"
format = "[\$all_status\$ahead_behind](\$style)"
conflicted = "󰞇 "
ahead = "󱓊 \${count}"
behind = "󱓋 \${count}"
diverged = "󰜘 \${ahead_count} 󰜙 \${behind_count}"
up_to_date = "󱓏 "
untracked = "󰋖 "
stashed = "󰉓 "
modified = "󰷈 "
staged = "󰐗 "
renamed = "󰑕 "
deleted = "󰗨 "

[character]
success_symbol = "[❯](bold fg:$(hex '.[$style].semantic.success'))"
error_symbol = "[❯](bold fg:$(hex '.[$style].semantic.danger'))"
vimcmd_symbol = "[❮](bold fg:$(hex '.[$style].semantic.accentAlt'))"
EOF
}

write_tmux_config() {
  prepare_target "$current_dir/tmux.conf"
  cat > "$current_dir/tmux.conf" <<EOF
# Generated by theme-select from $style.
set -g status-style "bg=$(hex '.[$style].semantic.background'),fg=$(hex '.[$style].semantic.foreground')"
set -g window-status-format "#[fg=$(hex '.[$style].semantic.muted'),bg=$(hex '.[$style].semantic.background')] #I "
set -g window-status-current-format "#[fg=$(hex '.[$style].semantic.background'),bg=$(hex '.[$style].semantic.accent'),bold] #I #[fg=$(hex '.[$style].semantic.accent'),bg=$(hex '.[$style].semantic.background')]"
set -g status-left "#[fg=$(hex '.[$style].semantic.muted'),bg=$(hex '.[$style].semantic.surface')]  #S #[fg=$(hex '.[$style].semantic.foreground'),bg=$(hex '.[$style].semantic.surface')] #{b:pane_current_path} #[fg=$(hex '.[$style].semantic.muted'),bg=$(hex '.[$style].semantic.background')] "
set -g status-right "#{prefix_highlight}#[fg=$(hex '.[$style].semantic.muted'),bg=$(hex '.[$style].semantic.background')]  #{user}   #H "
set -g @prefix_highlight_fg '$(hex '.[$style].semantic.background')'
set -g @prefix_highlight_bg '$(hex '.[$style].semantic.accent')'
set -g @prefix_highlight_copy_mode_attr 'fg=$(hex '.[$style].semantic.background'),bg=$(hex '.[$style].semantic.accentAlt'),bold'
set -g message-style "fg=$(hex '.[$style].semantic.foreground'),bg=$(hex '.[$style].semantic.surfaceStrong')"
set -g message-command-style "fg=$(hex '.[$style].semantic.accent'),bg=$(hex '.[$style].semantic.surfaceStrong')"
set -g mode-style "fg=$(hex '.[$style].semantic.background'),bg=$(hex '.[$style].semantic.accent'),bold"
set -g menu-style "fg=$(hex '.[$style].semantic.foreground'),bg=$(hex '.[$style].semantic.surface')"
set -g menu-selected-style "fg=$(hex '.[$style].semantic.background'),bg=$(hex '.[$style].semantic.accent'),bold"
set -g menu-border-style "fg=$(hex '.[$style].semantic.borderActive'),bg=$(hex '.[$style].semantic.surface')"
set -g popup-style "fg=$(hex '.[$style].semantic.foreground'),bg=$(hex '.[$style].semantic.surface')"
set -g popup-border-style "fg=$(hex '.[$style].semantic.borderActive'),bg=$(hex '.[$style].semantic.surface')"
set -g pane-border-style "fg=$(hex '.[$style].semantic.border')"
set -g pane-active-border-style "fg=$(hex '.[$style].semantic.borderActive')"
EOF
}
write_env() {
  local gtk_theme
  gtk_theme="$(gtk_env_theme)"

  prepare_target "$current_dir/env"
  cat > "$current_dir/env" <<EOF
# Generated by theme-select from $style.
export SKY_THEME=$style
export BAT_THEME=Sky
export BAT_STYLE="numbers,changes,header"
export STARSHIP_CONFIG="$current_dir/starship.toml"
export GTK_THEME=$gtk_theme
export GTK2_RC_FILES="$config_home/gtk-2.0/gtkrc"
export QT_STYLE_OVERRIDE=fusion
export QT_QPA_PLATFORMTHEME=qt5ct
export FZF_DEFAULT_OPTS='--color=fg:$(hex '.[$style].semantic.foreground'),bg:$(hex '.[$style].semantic.background'),hl:$(hex '.[$style].semantic.warning'),fg+:$(hex '.[$style].semantic.foreground'),bg+:$(hex '.[$style].semantic.surfaceStrong'),hl+:$(hex '.[$style].semantic.warning'),info:$(hex '.[$style].semantic.accent'),prompt:$(hex '.[$style].semantic.accent'),pointer:$(hex '.[$style].semantic.accent'),marker:$(hex '.[$style].semantic.success'),spinner:$(hex '.[$style].semantic.accent'),header:$(hex '.[$style].semantic.muted'),border:$(hex '.[$style].semantic.border')'
EOF
}
