;;; sky-theme-common.el -*- lexical-binding: t; -*-

(defun sky--color (name colors)
  (alist-get name colors))

(defun sky-define-theme (theme colors)
  "Define THEME from Sky COLORS."
  (let* ((bg (sky--color 'bg colors))
         (bg-alt (sky--color 'bg-alt colors))
         (surface (sky--color 'surface colors))
         (surface-strong (sky--color 'surface-strong colors))
         (border (sky--color 'border colors))
         (border-active (sky--color 'border-active colors))
         (fg (sky--color 'fg colors))
         (fg-alt (sky--color 'fg-alt colors))
         (muted (sky--color 'muted colors))
         (accent (sky--color 'accent colors))
         (accent-alt (sky--color 'accent-alt colors))
         (success (sky--color 'success colors))
         (warning (sky--color 'warning colors))
         (danger (sky--color 'danger colors))
         (selection-fg (sky--color 'selection-fg colors))
         (selection-bg (sky--color 'selection-bg colors))
         (string (sky--color 'string colors))
         (function (sky--color 'function colors))
         (keyword (sky--color 'keyword colors))
         (number (sky--color 'number colors))
         (type (sky--color 'type colors))
         (builtin (sky--color 'builtin colors))
         (preprocessor (sky--color 'preprocessor colors))
         (comment (sky--color 'comment colors))
         (black (sky--color 'black colors))
         (red (sky--color 'red colors))
         (green (sky--color 'green colors))
         (yellow (sky--color 'yellow colors))
         (blue (sky--color 'blue colors))
         (magenta (sky--color 'magenta colors))
         (cyan (sky--color 'cyan colors))
         (white (sky--color 'white colors)))
    (custom-theme-set-faces
     theme
     `(default ((t (:background ,bg :foreground ,fg))))
     `(cursor ((t (:background ,accent))))
     `(fringe ((t (:background ,bg :foreground ,muted))))
     `(highlight ((t (:background ,surface))))
     `(hl-line ((t (:background ,surface))))
     `(region ((t (:background ,selection-bg :foreground ,selection-fg))))
     `(secondary-selection ((t (:background ,surface-strong :foreground ,fg))))
     `(lazy-highlight ((t (:background ,surface-strong :foreground ,fg))))
     `(isearch ((t (:background ,warning :foreground ,selection-fg :weight bold))))
     `(match ((t (:background ,surface-strong :foreground ,accent :weight bold))))
     `(minibuffer-prompt ((t (:foreground ,accent :weight bold))))
     `(escape-glyph ((t (:foreground ,warning))))
     `(homoglyph ((t (:foreground ,warning))))
     `(link ((t (:foreground ,accent :underline t))))
     `(link-visited ((t (:foreground ,accent-alt :underline t))))
     `(error ((t (:foreground ,danger :weight bold))))
     `(warning ((t (:foreground ,warning :weight bold))))
     `(success ((t (:foreground ,success :weight bold))))
     `(shadow ((t (:foreground ,muted))))
     `(tooltip ((t (:background ,surface-strong :foreground ,fg))))
     `(vertical-border ((t (:foreground ,border))))
     `(window-divider ((t (:foreground ,border))))
     `(window-divider-first-pixel ((t (:foreground ,border))))
     `(window-divider-last-pixel ((t (:foreground ,border))))
     `(line-number ((t (:background ,bg :foreground ,muted))))
     `(line-number-current-line ((t (:background ,bg :foreground ,accent :weight bold))))
     `(font-lock-builtin-face ((t (:foreground ,builtin :weight medium))))
     `(font-lock-comment-face ((t (:foreground ,comment :slant italic))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,comment :slant italic))))
     `(font-lock-constant-face ((t (:foreground ,number))))
     `(font-lock-doc-face ((t (:foreground ,string))))
     `(font-lock-function-name-face ((t (:foreground ,function))))
     `(font-lock-keyword-face ((t (:foreground ,keyword :weight bold))))
     `(font-lock-negation-char-face ((t (:foreground ,warning :weight bold))))
     `(font-lock-number-face ((t (:foreground ,number))))
     `(font-lock-preprocessor-face ((t (:foreground ,preprocessor))))
     `(font-lock-regexp-grouping-backslash ((t (:foreground ,warning :weight bold))))
     `(font-lock-regexp-grouping-construct ((t (:foreground ,accent :weight bold))))
     `(font-lock-string-face ((t (:foreground ,string))))
     `(font-lock-type-face ((t (:foreground ,type))))
     `(font-lock-variable-name-face ((t (:foreground ,accent-alt))))
     `(font-lock-warning-face ((t (:foreground ,danger :weight bold))))
     `(mode-line ((t (:background ,surface :foreground ,fg :box nil))))
     `(mode-line-inactive ((t (:background ,bg :foreground ,muted :box nil))))
     `(mode-line-buffer-id ((t (:foreground ,fg :weight bold))))
     `(header-line ((t (:background ,surface :foreground ,fg :box nil))))
     `(tab-line ((t (:background ,bg-alt :foreground ,fg :box nil))))
     `(tab-line-tab ((t (:background ,surface :foreground ,fg :box nil))))
     `(tab-line-tab-current ((t (:background ,surface-strong :foreground ,fg :box nil :weight bold))))
     `(tab-line-tab-inactive ((t (:background ,bg-alt :foreground ,muted :box nil))))
     `(show-paren-match ((t (:background ,surface-strong :foreground ,accent :weight bold))))
     `(show-paren-mismatch ((t (:background ,danger :foreground ,selection-fg :weight bold))))
     `(trailing-whitespace ((t (:background ,danger))))
     `(whitespace-space ((t (:foreground ,border))))
     `(whitespace-tab ((t (:foreground ,border))))
     `(whitespace-newline ((t (:foreground ,border))))
     `(whitespace-trailing ((t (:background ,danger :foreground ,selection-fg))))
     `(solaire-default-face ((t (:background ,bg-alt :foreground ,fg))))
     `(solaire-fringe-face ((t (:background ,bg-alt :foreground ,muted))))
     `(solaire-line-number-face ((t (:background ,bg-alt :foreground ,muted))))
     `(solaire-hl-line-face ((t (:background ,surface))))
     `(doom-modeline-bar ((t (:background ,accent))))
     `(doom-modeline-bar-inactive ((t (:background ,border))))
     `(doom-modeline-buffer-file ((t (:foreground ,fg :weight medium))))
     `(doom-modeline-buffer-major-mode ((t (:foreground ,accent))))
     `(doom-modeline-buffer-minor-mode ((t (:foreground ,muted))))
     `(doom-modeline-buffer-modified ((t (:foreground ,warning :weight bold))))
     `(doom-modeline-info ((t (:foreground ,success))))
     `(doom-modeline-warning ((t (:foreground ,warning))))
     `(doom-modeline-urgent ((t (:foreground ,danger))))
     `(doom-modeline-debug ((t (:foreground ,warning))))
     `(doom-dashboard-banner ((t (:foreground ,accent))))
     `(doom-dashboard-footer ((t (:foreground ,muted))))
     `(doom-dashboard-footer-icon ((t (:foreground ,accent))))
     `(doom-dashboard-menu-desc ((t (:foreground ,fg))))
     `(doom-dashboard-menu-title ((t (:foreground ,accent :weight bold))))
     `(which-key-key-face ((t (:foreground ,accent :weight bold))))
     `(which-key-group-description-face ((t (:foreground ,keyword))))
     `(which-key-command-description-face ((t (:foreground ,fg))))
     `(which-key-local-map-description-face ((t (:foreground ,success))))
     `(which-key-separator-face ((t (:foreground ,muted))))
     `(completions-common-part ((t (:foreground ,accent :weight bold))))
     `(completions-first-difference ((t (:foreground ,warning :weight bold))))
     `(vertico-current ((t (:background ,surface-strong :foreground ,fg))))
     `(marginalia-documentation ((t (:foreground ,muted))))
     `(marginalia-key ((t (:foreground ,accent))))
     `(marginalia-symbol ((t (:foreground ,accent-alt))))
     `(orderless-match-face-0 ((t (:foreground ,accent :weight bold))))
     `(orderless-match-face-1 ((t (:foreground ,warning :weight bold))))
     `(orderless-match-face-2 ((t (:foreground ,success :weight bold))))
     `(orderless-match-face-3 ((t (:foreground ,danger :weight bold))))
     `(company-tooltip ((t (:background ,surface :foreground ,fg))))
     `(company-tooltip-selection ((t (:background ,surface-strong :foreground ,fg))))
     `(company-tooltip-common ((t (:foreground ,accent :weight bold))))
     `(company-tooltip-annotation ((t (:foreground ,muted))))
     `(company-scrollbar-bg ((t (:background ,surface))))
     `(company-scrollbar-fg ((t (:background ,border-active))))
     `(flycheck-error ((t (:underline (:style wave :color ,danger)))))
     `(flycheck-warning ((t (:underline (:style wave :color ,warning)))))
     `(flycheck-info ((t (:underline (:style wave :color ,success)))))
     `(flycheck-inline-error ((t (:foreground ,danger :weight bold))))
     `(flycheck-inline-warning ((t (:foreground ,warning :weight bold))))
     `(flycheck-inline-info ((t (:foreground ,success :weight bold))))
     `(flyspell-incorrect ((t (:underline (:style wave :color ,danger)))))
     `(flyspell-duplicate ((t (:underline (:style wave :color ,warning)))))
     `(lsp-face-highlight-read ((t (:background ,surface-strong :foreground ,fg))))
     `(lsp-face-highlight-textual ((t (:background ,surface-strong :foreground ,fg))))
     `(lsp-face-highlight-write ((t (:background ,surface-strong :foreground ,fg :weight bold))))
     `(lsp-ui-doc-background ((t (:background ,surface))))
     `(lsp-ui-doc-header ((t (:background ,surface-strong :foreground ,fg :weight bold))))
     `(org-block ((t (:background ,surface :foreground ,fg))))
     `(org-block-begin-line ((t (:background ,surface :foreground ,muted))))
     `(org-block-end-line ((t (:background ,surface :foreground ,muted))))
     `(org-code ((t (:foreground ,accent-alt))))
     `(org-date ((t (:foreground ,accent :underline t))))
     `(org-document-info ((t (:foreground ,fg-alt))))
     `(org-document-title ((t (:foreground ,accent :weight bold :height 1.3))))
     `(org-done ((t (:foreground ,success :weight bold))))
     `(org-headline-done ((t (:foreground ,muted))))
     `(org-hide ((t (:foreground ,bg))))
     `(org-level-1 ((t (:foreground ,accent :weight bold :height 1.2))))
     `(org-level-2 ((t (:foreground ,accent-alt :weight bold :height 1.1))))
     `(org-level-3 ((t (:foreground ,success :weight bold))))
     `(org-level-4 ((t (:foreground ,warning :weight bold))))
     `(org-level-5 ((t (:foreground ,type :weight bold))))
     `(org-level-6 ((t (:foreground ,builtin :weight bold))))
     `(org-link ((t (:foreground ,accent :underline t))))
     `(org-meta-line ((t (:foreground ,comment :slant italic))))
     `(org-special-keyword ((t (:foreground ,muted))))
     `(org-table ((t (:foreground ,accent-alt))))
     `(org-todo ((t (:foreground ,danger :weight bold))))
     `(org-verbatim ((t (:foreground ,warning))))
     `(markdown-code-face ((t (:background ,surface :foreground ,fg))))
     `(markdown-header-face ((t (:foreground ,accent :weight bold))))
     `(markdown-header-face-1 ((t (:foreground ,accent :weight bold :height 1.2))))
     `(markdown-header-face-2 ((t (:foreground ,accent-alt :weight bold :height 1.1))))
     `(magit-section-heading ((t (:foreground ,accent :weight bold))))
     `(magit-branch-current ((t (:foreground ,accent :weight bold))))
     `(magit-branch-local ((t (:foreground ,accent-alt))))
     `(magit-branch-remote ((t (:foreground ,success))))
     `(magit-diff-added ((t (:background ,surface :foreground ,success))))
     `(magit-diff-added-highlight ((t (:background ,surface-strong :foreground ,success))))
     `(magit-diff-removed ((t (:background ,surface :foreground ,danger))))
     `(magit-diff-removed-highlight ((t (:background ,surface-strong :foreground ,danger))))
     `(magit-diff-context ((t (:background ,bg :foreground ,fg-alt))))
     `(magit-diff-context-highlight ((t (:background ,surface :foreground ,fg))))
     `(magit-diff-file-heading ((t (:foreground ,fg :weight bold))))
     `(magit-diff-hunk-heading ((t (:background ,surface :foreground ,muted))))
     `(magit-diff-hunk-heading-highlight ((t (:background ,surface-strong :foreground ,fg))))
     `(diff-added ((t (:background ,surface :foreground ,success))))
     `(diff-removed ((t (:background ,surface :foreground ,danger))))
     `(diff-changed ((t (:background ,surface :foreground ,warning))))
     `(diff-header ((t (:background ,surface :foreground ,fg))))
     `(diff-file-header ((t (:background ,surface-strong :foreground ,fg :weight bold))))
     `(dired-directory ((t (:foreground ,accent :weight bold))))
     `(dired-flagged ((t (:foreground ,danger))))
     `(dired-header ((t (:foreground ,accent :weight bold))))
     `(dired-ignored ((t (:foreground ,muted))))
     `(dired-marked ((t (:foreground ,warning :weight bold))))
     `(dired-perm-write ((t (:foreground ,warning))))
     `(dired-symlink ((t (:foreground ,accent-alt :weight bold))))
     `(dired-warning ((t (:foreground ,danger :weight bold))))
     `(evil-goggles-default-face ((t (:background ,surface-strong :foreground ,fg :weight bold))))
     `(evil-goggles-yank-face ((t (:background ,accent :foreground ,selection-fg :weight bold))))
     `(evil-goggles-paste-face ((t (:background ,success :foreground ,selection-fg :weight bold))))
     `(evil-goggles-delete-face ((t (:background ,danger :foreground ,selection-fg :weight bold))))
     `(evil-goggles-change-face ((t (:background ,warning :foreground ,selection-fg :weight bold))))
     `(evil-goggles-indent-face ((t (:background ,accent-alt :foreground ,selection-fg :weight bold))))
     `(evil-goggles-join-face ((t (:background ,builtin :foreground ,selection-fg :weight bold))))
     `(avy-background-face ((t (:foreground ,muted))))
     `(avy-lead-face ((t (:background ,accent :foreground ,selection-fg :weight bold))))
     `(avy-lead-face-0 ((t (:background ,warning :foreground ,selection-fg :weight bold))))
     `(avy-lead-face-1 ((t (:background ,success :foreground ,selection-fg :weight bold))))
     `(avy-lead-face-2 ((t (:background ,danger :foreground ,selection-fg :weight bold)))))
    (custom-theme-set-variables
     theme
     `(ansi-color-names-vector [,black ,red ,green ,yellow ,blue ,magenta ,cyan ,white])
     `(ansi-term-color-vector [,black ,red ,green ,yellow ,blue ,magenta ,cyan ,white])
     `(fci-rule-color ,border)
     `(vc-annotate-color-map
       '((20 . ,danger)
         (40 . ,warning)
         (60 . ,success)
         (80 . ,accent)
         (100 . ,accent-alt)
         (120 . ,muted)
         (140 . ,fg)))
     `(vc-annotate-very-old-color nil))))

(provide 'sky-theme-common)
