;;; sky-dark-theme.el -*- lexical-binding: t; -*-

(require 'sky-theme-common)

(deftheme sky-dark "SkyDark theme.")

(sky-define-theme
 'sky-dark
 '((bg . "#1a1d21")
   (bg-alt . "#171a1e")
   (surface . "#22262b")
   (surface-strong . "#282c34")
   (border . "#3d424a")
   (border-active . "#b4c0c8")
   (fg . "#f0efeb")
   (fg-alt . "#ccc4b4")
   (muted . "#676d77")
   (accent . "#b4c0c8")
   (accent-alt . "#b4bcc4")
   (success . "#b8c4b8")
   (warning . "#d4ccb4")
   (danger . "#cdacac")
   (selection-fg . "#1a1d21")
   (selection-bg . "#b4c0c8")
   (string . "#b8c4b8")
   (function . "#b4c0c8")
   (keyword . "#b4bcc4")
   (number . "#d4ccb4")
   (type . "#d4ccb4")
   (builtin . "#b4c4bc")
   (preprocessor . "#ccc4b4")
   (comment . "#676d77")
   (black . "#22262b")
   (red . "#cdacac")
   (green . "#b8c4b8")
   (yellow . "#d4ccb4")
   (blue . "#b4bcc4")
   (magenta . "#ccc4b4")
   (cyan . "#b4c0c8")
   (white . "#f0efeb")))

(provide-theme 'sky-dark)
