;;; sk-theme.el --- Sky theme skeleton -*- lexical-binding: t; -*-

(defconst sk/theme-colors
  '((foreground . "#f0efeb")
    (foreground-alt . "#ccc4b4")
    (background . "#1a1d21")
    (background-alt . "#171a1e")
    (surface . "#22262b")
    (surface-strong . "#282c34")
    (border . "#3d424a")
    (border-active . "#b4c0c8")
    (accent . "#b4c0c8")
    (accent-alt . "#b4bcc4")
    (muted . "#676d77")
    (success . "#b8c4b8")
    (warning . "#d4ccb4")
    (danger . "#cdacac")
    (selection-foreground . "#1a1d21")
    (selection-background . "#b4c0c8")
    (string . "#b8c4b8")
    (function . "#b4c0c8")
    (keyword . "#b4bcc4")
    (number . "#d4ccb4")
    (type . "#d4ccb4")
    (builtin . "#b4c4bc")
    (comment . "#676d77"))
  "Sky Night color tokens used by the clean Emacs config.")

(defun sk/theme-color (name)
  "Return Sky color token NAME."
  (alist-get name sk/theme-colors))

(deftheme sky-night "Sky Night theme for the clean Emacs experiment.")

(let ((bg "#1a1d21")
      (bg-dim "#171a1e")
      (bg-alt "#22262b")
      (surface-strong "#282c34")
      (fg "#f0efeb")
      (fg-alt "#c8d0d8")
      (muted "#9aa1ac")
      (border "#3d424a")
      (accent "#b4c0c8")
      (accent-alt "#b4bcc4")
      (string "#a8d8b0")
      (function "#8ecae6")
      (keyword "#c4a7e7")
      (number "#f2cc8f")
      (type "#94d2bd")
      (builtin "#b8e0d2")
      (success "#a8d8b0")
      (warning "#e5989b")
      (danger "#ff8a8a"))
  (custom-theme-set-faces
   'sky-night
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,accent))))
   `(fringe ((t (:background ,bg :foreground ,muted))))
   `(region ((t (:background ,accent :foreground ,bg))))
   `(mode-line ((t (:background ,bg-alt :foreground ,fg :box nil))))
   `(mode-line-inactive ((t (:background ,bg-dim :foreground ,muted :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,fg :weight bold))))
   `(minibuffer-prompt ((t (:foreground ,accent :weight bold))))
   `(font-lock-comment-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-string-face ((t (:foreground ,string))))
   `(font-lock-function-name-face ((t (:foreground ,function))))
   `(font-lock-keyword-face ((t (:foreground ,keyword :weight bold))))
   `(font-lock-constant-face ((t (:foreground ,number))))
   `(font-lock-type-face ((t (:foreground ,type))))
   `(font-lock-builtin-face ((t (:foreground ,builtin))))
   `(font-lock-warning-face ((t (:foreground ,warning :weight bold))))
   `(doom-modeline ((t (:background ,bg-alt :foreground ,fg))))
   `(doom-modeline-bar ((t (:background ,accent))))
   `(doom-modeline-bar-inactive ((t (:background ,bg-dim))))
   `(doom-modeline-panel ((t (:background ,surface-strong :foreground ,fg))))
   `(doom-modeline-highlight ((t (:foreground ,accent :weight bold))))
   `(doom-modeline-emphasis ((t (:foreground ,fg :weight bold))))
   `(doom-modeline-buffer-path ((t (:foreground ,fg-alt))))
   `(doom-modeline-buffer-file ((t (:foreground ,fg :weight medium))))
   `(doom-modeline-buffer-modified ((t (:foreground ,warning :weight bold))))
   `(doom-modeline-buffer-major-mode ((t (:foreground ,accent))))
   `(doom-modeline-buffer-minor-mode ((t (:foreground ,muted))))
   `(doom-modeline-project-name ((t (:foreground ,fg-alt))))
   `(doom-modeline-project-parent-dir ((t (:foreground ,muted))))
   `(doom-modeline-project-dir ((t (:foreground ,fg-alt))))
   `(doom-modeline-project-root-dir ((t (:foreground ,accent :weight bold))))
   `(doom-modeline-vcs-default ((t (:foreground ,fg-alt))))
   `(doom-modeline-lsp-running ((t (:foreground ,accent))))
   `(doom-modeline-lsp-success ((t (:foreground ,success))))
   `(doom-modeline-lsp-warning ((t (:foreground ,warning))))
   `(doom-modeline-lsp-error ((t (:foreground ,danger :weight bold))))
   `(doom-modeline-evil-normal-state ((t (:foreground ,accent :weight bold))))
   `(doom-modeline-evil-insert-state ((t (:foreground ,success :weight bold))))
   `(doom-modeline-evil-visual-state ((t (:foreground ,warning :weight bold))))
   `(doom-modeline-evil-replace-state ((t (:foreground ,danger :weight bold))))
   `(doom-modeline-evil-motion-state ((t (:foreground ,accent-alt :weight bold))))
   `(doom-modeline-evil-emacs-state ((t (:foreground ,fg-alt :weight bold))))
   `(doom-modeline-info ((t (:foreground ,success))))
   `(doom-modeline-warning ((t (:foreground ,warning))))
   `(doom-modeline-urgent ((t (:foreground ,danger))))
   `(doom-modeline-debug ((t (:foreground ,warning))))
   `(vertical-border ((t (:foreground ,border))))))

(provide-theme 'sky-night)

(defun sk/load-theme ()
  "Load the Sky Night theme."
  (interactive)
  (enable-theme 'sky-night))

(provide 'sk-theme)

;;; sk-theme.el ends here
