preload = ~/Downloads/3840x2160-1375420-anime-school-girl-sunset-beach-scenery-4k-pc.jpg
#if more than one preload is desired then continue to preload other backgrounds
preload = ~/Downloads/wallpapersden.com_happiest-anime-girl-hd-ai-art_1952x1120.jpg
# .. more preloads
 
#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = ,~/Downloads/3840x2160-1375420-anime-school-girl-sunset-beach-scenery-4k-pc.jpg
#if more than one monitor in use, can load a 2nd image
#wallpaper = monitor2,/path/to/next_image.png
# .. more monitors
 
#enable splash text rendering over the wallpaper
splash = true
 
#fully disable ipc
# ipc = off

