#!/usr/bin/env bash
set -euo pipefail

wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
status=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)

if [[ "$status" == *"[MUTED]"* ]]; then
    icon="󰍭"
    title="Mic muted"
else
    icon="󰍬"
    title="Mic active"
fi

qs ipc call osd show "$icon" "$title" -1 >/dev/null 2>&1 || true
