{
  imports = [
    ./base.nix
    ./networking.nix
    ./power.nix
    ./input.nix
    ./users.nix
    ./gaming.nix
    ./packages.nix
    ./programs/bat.nix
    ./programs/nvim
    ./services/ollama.nix
    ./desktop/hyprland.nix
    ./audio-config.nix
    ./nvidia.nix
    ./boot.nix
    ./fonts.nix
    ./clipboard.nix
  ];
}
